package com.example.multipaymentgateway.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Data Transfer Object for outgoing payment responses.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class PaymentResponse {

    private String transactionId; // Unique ID generated by our system or the gateway
    private String gatewayTransactionId; // Transaction ID from the specific payment gateway
    private String status; // e.g., "SUCCESS", "PENDING", "FAILED", "REFUNDED"
    private String message; // User-friendly message about the transaction status
    private String gatewayName; // Name of the gateway that processed the transaction (e.g., "stripe", "razorpay")
    private BigDecimal amount;
    private String currency;
    private LocalDateTime timestamp;

    // Optional: For redirect scenarios (e.g., 3D Secure)
    private String redirectUrl;

    // Optional: Any additional data from the gateway
    private Object gatewaySpecificResponse;

}
